### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kenju** [kenju/go-minruby#6]
## Roadmap for v1.0.0

- [ ] improve parsing logic
  - more elegant way to parse `;` and `\n`
- [ ] support while
- [ ] support function definition
- [ ] support Array
- [ ] support Hash

**Comment by kenju** [comment]
## Roadmap for v2.0.0

- [ ] compilation w/ VM instead of simple interpretation
